services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: example
    networks:
      - hypertube
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "example", "-u", "user"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    ports:
      - 5432:5432

  server:
    depends_on:
      - postgres
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - hypertube
    volumes:
      - ./server/:/app
      - ./downloads:/app/downloads
      - ./hls_output:/app/hls_output
    env_file:
      - .env
    environment:
      # CORS_ORIGINS: "http://localhost:4200,http://localhost:8080"
      # UI_ADDRESS: http://localhost:4200
      CORS_ORIGINS: "http://localhost:3000,http://localhost:4200,http://localhost:8080"
      UI_ADDRESS: http://localhost:3000
      MOVIE_APIS_TMDB_API_KEY: "${TMDB_API_KEY}"
      MOVIE_APIS_OMDB_API_KEY: "${OMDB_API_KEY}"
      DOWNLOADS_DIRECTORY: "/app/downloads"
      STREAMING_DOWNLOAD_DIR: "/app/downloads"
      STREAMING_TMDB_API_KEY: "${TMDB_API_KEY}"
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    expose:
      - "3000"
    environment:
      NEXT_PUBLIC_API_BASE: "/api"
      NODE_ENV: "production"
    networks:
      - hypertube
    depends_on:
      - server
    volumes:
      - ./client/:/app

  nginx:
    image: nginx:1.27-alpine
    container_name: cine_thos_nginx
    depends_on:
      - client
      - server
    ports:
      - "80:80"
    networks:
      - hypertube
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

networks:
  hypertube:
    driver: bridge
