services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: example
    networks:
      - hypertube
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U user -d example -h 127.0.0.1 -p 5432 || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    ports:
      - 5432:5432

  server:
    depends_on:
      postgres:
        condition: service_healthy
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - hypertube
    volumes:
      - ./server/:/app
      - ./downloads:/app/downloads
    env_file:
      - .env
    environment:
      CORS_ORIGINS: "http://localhost:3000,http://localhost:8080"
      UI_ADDRESS: "http://localhost:3000"
      MOVIE_APIS_TMDB_API_KEY: "${TMDB_API_KEY}"
      MOVIE_APIS_OMDB_API_KEY: "${OMDB_API_KEY}"
      DOWNLOADS_DIRECTORY: "/app/downloads"
      STREAMING_DOWNLOAD_DIR: "/app/downloads"
      STREAMING_TMDB_API_KEY: "${TMDB_API_KEY}"
  # web:
  #   build:
  #     context: ./client
  #     dockerfile: Dockerfile
  #   expose:
  #     - "3000"
  #     NEXT_PUBLIC_API_BASE: "/api"
  #     NODE_ENV: "production"
  #   networks:
  #     - hypertube
  #   depends_on:
  #     - server

  # nginx:
  #   image: nginx:1.27-alpine
  #   container_name: cine_thos_nginx
  #   depends_on:
  #     - web
  #     - server
  #   ports:
  #     - "80:80"
  #   networks:
  #     - hypertube
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

networks:
  hypertube:
    driver: bridge
