services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: example
    networks:
      - hypertube
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "example", "-u", "user"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    ports:
      - 5432:5432
    profiles:
      - "default"
      - "prod"

  server:
    depends_on:
      - postgres
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - hypertube
    volumes:
      - ./server/:/app
    environment:
      # HTTP_PORT: 8081
      CORS_ORIGINS: "http://localhost:4200,http://localhost:8080"
    profiles:
      - "default"

  server-prod:
    depends_on:
      - postgres
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - hypertube
    environment:
      CORS_ORIGINS: "http://localhost:4200,http://localhost:8080"
    command: go run ./main.go
    profiles:
      - "prod"

networks:
  hypertube:
    driver: bridge
