# name: Test Frontend

# on:
#   push:
#   pull_request:

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4

#       - name: Setup Node.js and Npm
#         uses: actions/setup-node@v4
#         with:
#           node-version: "20"

#       - name: Install dependencies
#         working-directory: ./client
#         run: npm i

#       - name: Test
#         working-directory: ./client
#         run: npm run test
